WebApplication1/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models.Data;

namespace WebApplication1.Controllers
{
    public class ContactController : Controller
    {
        DBLAPTOPEntities db = new DBLAPTOPEntities();
        // GET: Contact
        [HttpPost]
        public ActionResult ContactPage(FormCollection contactForm)
        {

            Contact contact = new Contact();
            var title = contactForm["title"];
            var fullName = contactForm["fullName"];
            var email = contactForm["email"];
            var phone = contactForm["phonenumber"];
            var detail = contactForm["noidung"];
            contact.title = title;
            contact.fullName = fullName;
            contact.email = email;
            contact.detail = detail;
            contact.phone = phone;
            contact.dateCreate = DateTime.Now;
            contact.status = false;
            db.Contacts.Add(contact);
            db.SaveChanges();
            ViewBag.Notice = "<div class='alert alert-success text-center text-dark' role='alert'>Gửi liên hệ thành công</div>";
            return View();
        }

        public ActionResult ContactPage()
        {
            return View();
        }
    }
}

WebApplication1/Controllers/DiscountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models.Data;
namespace WebApplication1.Controllers
{
    public class DiscountController : Controller
    {
        DBLAPTOPEntities db = new DBLAPTOPEntities();
        // GET: Discount
        public ActionResult discountPage()
        {
            return View(db.Discounts.ToList());
        }
    }
}

WebApplication1/Controllers/PolicyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class PolicyController : Controller
    {
        // GET: Policy
        public ActionResult Policy()
        {
            return View();
        }

        public ActionResult Warranty()
        {
            return View();
        }

        public ActionResult Condition()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

WebApplication1/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models.Data;
using PagedList;
using PagedList.Mvc;
namespace WebApplication1.Controllers
{
    public class ProductController : Controller
    {
        DBLAPTOPEntities db = new DBLAPTOPEntities();
        int pageSize = 6;
        // GET: Product
        public ActionResult ProductPage(int? page)
        {
            int pageNum = (page ?? 1);
            var products = db.Products.ToList();

            ViewBag.Categories = db.Categories.ToList();
            ViewBag.Brands = db.Brands.ToList();
            ViewBag.productTitle = "Tất cả sản phẩm";

            return View(products.ToPagedList(pageNum, pageSize));
        }

        public ActionResult filterByCategory(int id, int? page)
        {
            int pageNum = (page ?? 1);
            var products = db.Products.Where(p => p.categoryID == id).ToList();

            ViewBag.Categories = db.Categories.ToList();
            ViewBag.Brands = db.Brands.ToList();
            ViewBag.productTitle = db.Categories.Find(id).categoryName;
            return View("ProductPage", products.ToPagedList(pageNum, pageSize));
        }

        public ActionResult filterByBrand(int id, int? page)
        {
            int pageNum = (page ?? 1);
            var products = db.Products.Where(p => p.brandID == id).ToList();

            ViewBag.Categories = db.Categories.ToList();
            ViewBag.Brands = db.Brands.ToList();
            ViewBag.productTitle = "Laptop " + db.Brands.Find(id).brandName;

            return View("ProductPage", products.ToPagedList(pageNum, pageSize));
        }

        [HttpPost]
        public ActionResult Search(FormCollection frm, int? page)
        {
            string input = frm["search"];
            int pageNum = (page ?? 1);
            var products = db.Products.Where(p => p.productName.Contains(input)).ToList();

            ViewBag.Categories = db.Categories.ToList();
            ViewBag.Brands = db.Brands.ToList();
            ViewBag.productTitle = "Tìm kiếm sản phẩm theo " + "\"" + input +  "\"";
            return View("ProductPage", products.ToPagedList(pageNum, pageSize));
        }

        public ActionResult sortByDescending(int? page)
        {
            int pageNum = (page ?? 1);
            var products = db.Products.OrderByDescending(p => p.productPrice).ToList();

            ViewBag.productTitle = "Giá giảm dần";
            ViewBag.Categories = db.Categories.ToList();
            ViewBag.Brands = db.Brands.ToList();
            return View("ProductPage", products.ToPagedList(pageNum, pageSize));
        }

        public ActionResult sortByIncreasing(int? page)
        {
            int pageNum = (page ?? 1);
            var products = db.Products.OrderBy(p => p.productPrice).ToList();

            ViewBag.productTitle = "Giá tăng dần";
            ViewBag.Categories = db.Categories.ToList();
            ViewBag.Brands = db.Brands.ToList();
            return View("ProductPage", products.ToPagedList(pageNum, pageSize));
        }

        public ActionResult lastedProducts(int? page)
        {
            int pageNum = (page ?? 1);
            var products = db.Products.OrderByDescending(p => p.dateCreate).ToList();

            ViewBag.productTitle = "Sản phẩm mới nhất";
            ViewBag.Categories = db.Categories.ToList();
            ViewBag.Brands = db.Brands.ToList();
            return View("ProductPage", products.ToPagedList(pageNum, pageSize));
        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> THT Laptop Store </title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link href="~/fonts/css/fontawesome.min.css" rel="stylesheet" />
    <link href="~/fonts/css/brands.min.css" rel="stylesheet" />
    <link href="~/fonts/css/solid.min.css" rel="stylesheet" />
    <link href="~/fonts/css/regular.min.css" rel="stylesheet" />
    <link href="~/Public/css/style.css" rel="stylesheet" />
    <link href="~/Public/css/productDetail.css" rel="stylesheet" />
    <link rel="shortcut icon" href="~/images/logo/Designbolts-Free-Multimedia-Laptop.ico" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

</head>

<body>
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v11.0&appId=3976925969082352&autoLogAppEvents=1" nonce="WejoyIci"></script>
    <script>
        window.fbAsyncInit = function () {
            FB.init({
                appId: '3976925969082352',
                xfbml: true,
                version: 'v11.0'
            });
            FB.AppEvents.logPageView();
        };

        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) { return; }
            js = d.createElement(s); js.id = id;
            js.src = "https://connect.facebook.net/en_US/sdk.js";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
    <header>
        <nav class="navbar navbar-light bg-white p-0">
            <div class="container">
                <a class="navbar-brand p-0" href="@Url.Action("Index","Home")">
                    <img src="~/images/logo/213682375_509355140293215_4297729168636508658_n.png" alt="" style="width:290px; height:70px" />
                </a>
                <div class="nav-item d-inline-flex">
                    <marquee width="500px"><b>THT Store - Cam kết chính hãng - Uy tín - Chất lượng - 0989969919</b></marquee>
                </div>
                <div class="d-flex">
                    @Html.Action("customerPartial", "Customer")
                    @Html.Action("CartPartial", "Cart")
                </div>
            </div>
        </nav>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="background-color: #363636">
            <div class="container px-0">
                <button class="navbar-toggler border-white border-5" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav">

                        <li class="nav-item">
                            <a class="nav-link active" style="color: #F8F8FF; margin-left: 70px" href="@Url.Action("Index","Home")"><b>TRANG CHỦ</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color: #F8F8FF; margin-left: 20px" href="@Url.Action("About","Policy")"><b>GIỚI THIỆU</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color: #F8F8FF; margin-left: 20px" href="@Url.Action("ProductPage","Product")"><b>SẢN PHẨM</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color: #F8F8FF; margin-left: 20px" href="@Url.Action("discountPage","Discount")"><b>KHUYẾN MÃI</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color: #F8F8FF; margin-left: 20px" href="@Url.Action("Blog","Blog")"><b>TIN TỨC</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color: #F8F8FF; margin: 0px 20px" href="@Url.Action("ContactPage","Contact")"><b>LIÊN HỆ</b></a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" style="color: #F8F8FF;" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <b>CHÍNH SÁCH</b>
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li><a class="dropdown-item" href="@Url.Action("Policy","Policy")">Chính sách quy định chung</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("Condition","Policy")">Điều kiện bảo hành</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("Warranty","Policy")">Chính sách bảo hành</a></li>
                            </ul>
                        </li>
                        <li>
                            @using (Html.BeginForm("Search", "Product", FormMethod.Post, new { @class = "d-flex" }))
                            {
                                <input class="form-control me-2" type="search" name="search" placeholder="Tìm kiếm" aria-label="Search" style="width: 270px">
                                <button class="btn btn-light text-dark" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        @* Back to top *@
        <button onclick="topFunction()" id="myBtn" title="Go to top"><i class="fa fa-chevron-circle-up" aria-hidden="true"></i></button>
        <style>
            #myBtn {
                display: none;
                position: fixed;
                bottom: 20px;
                right: 15px;
                font-size: 20px;
                border: none;
                background-color: white;
                cursor: pointer;
                border-radius: 30px;
            }

                #myBtn:hover {
                    background-color: #0099FF;
                }
        </style>
        <script>
            // When the user scrolls down 20px from the top of the document, show the button
            window.onscroll = function () { scrollFunction() };
            function scrollFunction() {
                if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                    document.getElementById("myBtn").style.display = "block";
                } else {
                    document.getElementById("myBtn").style.display = "none";
                }
            }
            // When the user clicks on the button, scroll to the top of the document
            function topFunction() {
                document.body.scrollTop = 0;
                document.documentElement.scrollTop = 0;
            }
        </script>
    </header>

    <section id="main_content">
        @RenderBody()
    </section>

    <footer>
        <img src="~/images/bia/bia5.PNG" style="width:100%; height:100%" />
        <div class="container-fluid" style="background-color: #111111">

            <div class="container">
                <div class="row">

                    <div class="col-md-3 pt-3">
                        <a class="nav-link active" style="color: #F8F8FF"><b>CỬA HÀNG</b></a>

                        <iframe width="300"
                                height="200"
                                style="border:0"
                                loading="lazy"
                                allowfullscreen
                                src="https://maps.google.com/maps?width=631&amp;height=665&amp;hl=en&amp;saddr=Đại Học Hutech Khu E, Phường Tân Phú, Quận 9, Thành phố Hồ Chí Minh,
                                Vietnam&amp;daddr=Đại Học Hutech Khu E, Phường Tân Phú, Quận 9, Thành phố Hồ Chí Minh, Vietnam&amp;t=&amp;z=20&amp;ie=UTF8&amp;iwloc=B&amp;output=embed">
                        </iframe>




                    </div>
                    <div class="col-md-3 pt-3">
                        <a class="nav-link active" style="color: #F8F8FF"><b>CHÍNH SÁCH</b></a>
                        <a class="nav-link active" style="color: #BBBBBB" href="@Url.Action("About","Policy")"><b>Về chúng tôi</b></a>
                        <a class="nav-link active" style="color: #BBBBBB" href="@Url.Action("Policy","Policy")"><b>Chính sách quy định chung</b></a>
                        <a class="nav-link active" style="color: #BBBBBB" href="@Url.Action("Condition","Policy")"><b>Điều kiện bảo hành</b></a>
                        <a class="nav-link active" style="color: #BBBBBB" href="@Url.Action("Warranty","Policy")"><b>Chính sách bảo hành</b></a>
                        <a class="nav-link active" style="color: #BBBBBB" href="@Url.Action("ContactPage","Contact")"><b>Liên hệ</b></a>
                    </div>
                    <div class="col-md-3 pt-3">
                        <a class="nav-link active" style="color: #F8F8FF"><b>HỖ TRỢ</b></a>
                        <a class="nav-link active" style="color: #BBBBBB" href="tel:0989969919">Tổng đài tư vấn: 0989969919</a>
                        <a class="nav-link active" style="color: #BBBBBB" href="tel:0123456789">Tư vấn mua hàng: 0123456789</a>
                        <a class="nav-link active" style="color: #BBBBBB" href="tel:0163686839">Hỗ trợ kỹ thuật: 0163686839</a>
                        <a class="nav-link active" style="color: #BBBBBB" href="tel:0386969056">Phản hồi, góp ý: 0386969056</a>

                    </div>
                    <div class="col-3 pt-3">
                        <a class="nav-link active" style="color: #F8F8FF"><b>FANPAGE FACEBOOK</b></a>
                        <div class="fb-page" data-href="https://www.facebook.com/Laptop-THT-118931643278743" data-tabs="timeline"
                             data-width="300" data-height="200" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false"
                             data-show-facepile="true">
                            <blockquote cite="https://www.facebook.com/Laptop-THT-118931643278743" class="fb-xfbml-parse-ignore">
                                <a href="https://www.facebook.com/Laptop-THT-118931643278743">Laptop THT</a>
                            </blockquote>
                        </div>
                    </div>
                </div>
                <center class="nav-link active"><p>&copy; @DateTime.Now.Year Copyright: THT Store</p></center>
            </div>
        </div>
    </footer>

    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Public/js/CustomerDetail.js"></script>
    <div id="fb-root"></div>
    <div id="fb-customer-chat" class="fb-customerchat">
    </div>
    @RenderSection("scripts", required: false)
    <script>
        var chatbox = document.getElementById('fb-customer-chat');
        chatbox.setAttribute("page_id", "118931643278743");
        chatbox.setAttribute("attribution", "biz_inbox");

        window.fbAsyncInit = function () {
            FB.init({
                xfbml: true,
                version: 'v11.0'
            });
        };

        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = 'https://connect.facebook.net/vi_VN/sdk/xfbml.customerchat.js';
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
</body>
</html>