WebApplication1/Models/Data/Product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int productID { get; set; }
        public int categoryID { get; set; }
        public int brandID { get; set; }
        public string productName { get; set; }
        public int productPrice { get; set; }
        public string productDetail { get; set; }
        public string image { get; set; }
        public System.DateTime dateCreate { get; set; }
        public int amount { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}

WebApplication1/Areas/Admin/Controllers/ProductController.cs
using System;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models.Data;

namespace WebApplication1.Areas.Admin.Controllers
{
    public class ProductController : Controller
    {
        DBLAPTOPEntities db = new DBLAPTOPEntities();
        // GET: Admin/Product


        public ActionResult Index()
        {
            if (Session["userID"] == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var productList = db.Products.ToList();
            return View(productList);
        }

        public ActionResult Create()
        {
            if (Session["userID"] == null)
            {
                return RedirectToAction("Login", "Account");
            }
            ViewBag.Category = db.Categories.ToList();
            ViewBag.Brand = db.Brands.ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult createProduct(Product productInfo, HttpPostedFileBase ImageUpload)
        {
            productInfo.dateCreate = DateTime.Now;
            if (ImageUpload != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(ImageUpload.FileName);
                string extension = Path.GetExtension(ImageUpload.FileName);
                fileName += extension;
                productInfo.image = "~/images/sanpham/" + fileName;
                ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/images/sanpham"), fileName));
                db.Products.Add(productInfo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                productInfo.image = "~/images/sanpham/none.png";
                db.Products.Add(productInfo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (Session["userID"] == null || id == null)
            {
                return RedirectToAction("Login", "Account");
            }
            Product prod = db.Products.Find(id);
            ViewBag.Category = db.Categories.ToList();
            ViewBag.Brand = db.Brands.ToList();
            return View(prod);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(FormCollection frm)
        {
            var editedProd = db.Products.Find(Int32.Parse(frm["productID"]));
            editedProd.productName = frm["productName"];
            editedProd.categoryID = Int32.Parse(frm["categoryID"]);
            editedProd.brandID = Int32.Parse(frm["brandID"]);
            editedProd.productPrice = Int32.Parse(frm["productPrice"]);
            editedProd.amount = Int32.Parse(frm["amount"]);
            editedProd.productDetail = frm["productDetail"];
            editedProd.dateCreate = DateTime.Now;
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult Delete(int? id)
        {
            if (id == null || Session["userID"] == null)
            {
                return RedirectToAction("Login", "Account");
            }
            Product pro = db.Products.Find(id);
            db.Products.Remove(pro);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Detail(int? id)
        {
            if (id == null || Session["userID"] == null)
            {
                return RedirectToAction("Login", "Account");
            }
            Product pro = db.Products.Find(id);
            return View(pro);
        }

        public ActionResult uploadImage(FormCollection frm, HttpPostedFileBase ImageUpload)
        {
            var prod = db.Products.Find(Int32.Parse(frm["productID"]));
            if (ImageUpload != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(ImageUpload.FileName);
                string extension = Path.GetExtension(ImageUpload.FileName);
                fileName += extension;
                prod.image = "~/images/sanpham/" + fileName; ;
                ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/images/sanpham"), fileName));

                db.SaveChanges();

                return RedirectToAction("Edit", "Product", new { id = Int32.Parse(frm["productID"]) });
            }
            else
            {
                prod.image = "~/images/sanpham/none.png";
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }
    }
}

WebApplication1/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models.Data;
using PagedList;
using PagedList.Mvc;
namespace WebApplication1.Controllers
{
    public class ProductController : Controller
    {
        DBLAPTOPEntities db = new DBLAPTOPEntities();
        int pageSize = 6;
        // GET: Product
        public ActionResult ProductPage(int? page)
        {
            int pageNum = (page ?? 1);
            var products = db.Products.ToList();

            ViewBag.Categories = db.Categories.ToList();
            ViewBag.Brands = db.Brands.ToList();
            ViewBag.productTitle = "Tất cả sản phẩm";

            return View(products.ToPagedList(pageNum, pageSize));
        }

        public ActionResult filterByCategory(int id, int? page)
        {
            int pageNum = (page ?? 1);
            var products = db.Products.Where(p => p.categoryID == id).ToList();

            ViewBag.Categories = db.Categories.ToList();
            ViewBag.Brands = db.Brands.ToList();
            ViewBag.productTitle = db.Categories.Find(id).categoryName;
            return View("ProductPage", products.ToPagedList(pageNum, pageSize));
        }

        public ActionResult filterByBrand(int id, int? page)
        {
            int pageNum = (page ?? 1);
            var products = db.Products.Where(p => p.brandID == id).ToList();

            ViewBag.Categories = db.Categories.ToList();
            ViewBag.Brands = db.Brands.ToList();
            ViewBag.productTitle = "Laptop " + db.Brands.Find(id).brandName;

            return View("ProductPage", products.ToPagedList(pageNum, pageSize));
        }

        [HttpPost]
        public ActionResult Search(FormCollection frm, int? page)
        {
            string input = frm["search"];
            int pageNum = (page ?? 1);
            var products = db.Products.Where(p => p.productName.Contains(input)).ToList();

            ViewBag.Categories = db.Categories.ToList();
            ViewBag.Brands = db.Brands.ToList();
            ViewBag.productTitle = "Tìm kiếm sản phẩm theo " + "\"" + input +  "\"";
            return View("ProductPage", products.ToPagedList(pageNum, pageSize));
        }

        public ActionResult sortByDescending(int? page)
        {
            int pageNum = (page ?? 1);
            var products = db.Products.OrderByDescending(p => p.productPrice).ToList();

            ViewBag.productTitle = "Giá giảm dần";
            ViewBag.Categories = db.Categories.ToList();
            ViewBag.Brands = db.Brands.ToList();
            return View("ProductPage", products.ToPagedList(pageNum, pageSize));
        }

        public ActionResult sortByIncreasing(int? page)
        {
            int pageNum = (page ?? 1);
            var products = db.Products.OrderBy(p => p.productPrice).ToList();

            ViewBag.productTitle = "Giá tăng dần";
            ViewBag.Categories = db.Categories.ToList();
            ViewBag.Brands = db.Brands.ToList();
            return View("ProductPage", products.ToPagedList(pageNum, pageSize));
        }

        public ActionResult lastedProducts(int? page)
        {
            int pageNum = (page ?? 1);
            var products = db.Products.OrderByDescending(p => p.dateCreate).ToList();

            ViewBag.productTitle = "Sản phẩm mới nhất";
            ViewBag.Categories = db.Categories.ToList();
            ViewBag.Brands = db.Brands.ToList();
            return View("ProductPage", products.ToPagedList(pageNum, pageSize));
        }
    }
}

WebApplication1/Controllers/ProductDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models.Data;
namespace WebApplication1.Controllers
{
    public class ProductDetailController : Controller
    {
        // GET: ProductDetail
        DBLAPTOPEntities db = new DBLAPTOPEntities();
        public ActionResult ProductDetailPage(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }
            var selectedProduct = db.Products.Find(id);
            ViewBag.relativeProducts = getRelativeProducts(selectedProduct.categoryID);
            var request = HttpContext.Request.Url.AbsoluteUri;
            ViewBag.Url = request;
            return View(selectedProduct);
        }

        private List<Product> getRelativeProducts(int categoryID)
        {
            return db.Products.Where(p => p.categoryID == categoryID).Take(4).ToList();
        }
    }
}

WebApplication1/Views/Product/ProductPage.cshtml
@using WebApplication1.Models.Data
@using System.Globalization
@using PagedList.Mvc;
@model PagedList.PagedList<Product>

@{ ViewBag.Title = "Sản phẩm";
    Layout = "~/Views/Shared/_Layout.cshtml"; 
}

<div class="container">
    <div class="row">
        <div class="col-3 " style="margin-top:44px">
            <div class="list-group mb-3">
                <button type="button" class="list-group-item list-group-item-action active" aria-current="true">
                    Loại sản phẩm
                </button>
                @foreach (var item in (List<Category>)ViewBag.Categories)
                {
                    <a class="btn list-group-item list-group-item-action" href="@Url.Action("filterByCategory","Product",new {id = item.categoryID})">@item.categoryName</a>
                }
            </div>
            <div class="list-group">
                <button type="button" class="list-group-item list-group-item-action active" aria-current="true">
                    Thương hiệu
                </button>
                @foreach (var item in (List<Brand>)ViewBag.Brands)
                {
                    <a class="btn list-group-item list-group-item-action" href="@Url.Action("filterByBrand","Product",new {id = item.brandID })">@item.brandName</a>
                }
            </div>
        </div>
        <div class="col-9">
            <div class="row">
                <div class="col-md-10"></div>
                <div class="col-md-2">
                    <div class="dropdown" style="margin-left:70px">
                        <a class="btn btn-secondary dropdown-toggle btn-light float-end" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false" style="padding:5px">
                            Bộ lọc
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                            <li><a class="dropdown-item" href="@Url.Action("sortByDescending", "Product")"><i class="fas fa-chevron-down"></i>Giá giảm dần</a></li>
                            <li><a class="dropdown-item" href="@Url.Action("sortByIncreasing", "Product")"><i class="fas fa-chevron-up"></i>Giá tăng dần</a></li>
                            <li><a class="dropdown-item" href="@Url.Action("lastedProducts", "Product")">Mới nhất</a></li>
                        </ul>
                    </div>
                </div>
                <div class="container mb-3 border border-1 shadow rounded rounded-3">
                    <h4 class="text-center"><b>@ViewBag.productTitle <span>(@Model.ToList().Count)</span></b></h4>
                    <div class="row">
                        @foreach (var item in Model)
                        {
                            <div class="col-md-4 col-12">
                                <a href="@Url.Action("ProductDetailPage","ProductDetail",new {id = item.productID })" style="text-decoration: none;">
                                    <div class="card">
                                        <img src="@Url.Content(item.image)" class="card-img-top" alt="@Url.Content(item.image)">
                                        <div class="card-body">
                                            <p class="card-title text-dark" style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">@item.productName</p>
                                            <p class="card-text text-danger fw-bold float-start">
                                                @string.Format(new CultureInfo("vi-VN"), "{0:c}", item.productPrice)
                                            </p>
                                        </div>
                                    </div>
                                </a>
                                <hr />
                            </div>
                        }
                    </div>
                    <div class="MenuPage">
                        @Html.PagedListPager(Model, page => Url.Action("ProductPage", new { page = page }))
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .MenuPage li {
        display: inline;
        text-align: center;
    }

    .pagination a {
        color: black;
        float: left;
        padding: 8px 16px;
        text-decoration: none;
        transition: background-color .3s;
    }

        .pagination a.active {
            background-color: dodgerblue;
            color: white;
        }

        .pagination a:hover:not(.active) {
            background-color: #ddd;
        }
</style>